
spring:
  datasource:
    url: jdbc:h2:mem:agenda
    username: agenda
    password: agenda
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect